// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cityservice/cityService.proto

package go_micro_srv_CityService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProvinceData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProvinceName         string   `protobuf:"bytes,2,opt,name=province_name,json=provinceName,proto3" json:"province_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvinceData) Reset()         { *m = ProvinceData{} }
func (m *ProvinceData) String() string { return proto.CompactTextString(m) }
func (*ProvinceData) ProtoMessage()    {}
func (*ProvinceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{0}
}

func (m *ProvinceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvinceData.Unmarshal(m, b)
}
func (m *ProvinceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvinceData.Marshal(b, m, deterministic)
}
func (m *ProvinceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvinceData.Merge(m, src)
}
func (m *ProvinceData) XXX_Size() int {
	return xxx_messageInfo_ProvinceData.Size(m)
}
func (m *ProvinceData) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvinceData.DiscardUnknown(m)
}

var xxx_messageInfo_ProvinceData proto.InternalMessageInfo

func (m *ProvinceData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProvinceData) GetProvinceName() string {
	if m != nil {
		return m.ProvinceName
	}
	return ""
}

type ListProvinceData struct {
	Provinces            []*ProvinceData `protobuf:"bytes,1,rep,name=provinces,proto3" json:"provinces,omitempty"`
	Paging               *Paging         `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListProvinceData) Reset()         { *m = ListProvinceData{} }
func (m *ListProvinceData) String() string { return proto.CompactTextString(m) }
func (*ListProvinceData) ProtoMessage()    {}
func (*ListProvinceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{1}
}

func (m *ListProvinceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProvinceData.Unmarshal(m, b)
}
func (m *ListProvinceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProvinceData.Marshal(b, m, deterministic)
}
func (m *ListProvinceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProvinceData.Merge(m, src)
}
func (m *ListProvinceData) XXX_Size() int {
	return xxx_messageInfo_ListProvinceData.Size(m)
}
func (m *ListProvinceData) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProvinceData.DiscardUnknown(m)
}

var xxx_messageInfo_ListProvinceData proto.InternalMessageInfo

func (m *ListProvinceData) GetProvinces() []*ProvinceData {
	if m != nil {
		return m.Provinces
	}
	return nil
}

func (m *ListProvinceData) GetPaging() *Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{2}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ListCityResponse struct {
	Cities               []*CityData `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
	Paging               *Paging     `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCityResponse) Reset()         { *m = ListCityResponse{} }
func (m *ListCityResponse) String() string { return proto.CompactTextString(m) }
func (*ListCityResponse) ProtoMessage()    {}
func (*ListCityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{4}
}

func (m *ListCityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCityResponse.Unmarshal(m, b)
}
func (m *ListCityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCityResponse.Marshal(b, m, deterministic)
}
func (m *ListCityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCityResponse.Merge(m, src)
}
func (m *ListCityResponse) XXX_Size() int {
	return xxx_messageInfo_ListCityResponse.Size(m)
}
func (m *ListCityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCityResponse proto.InternalMessageInfo

func (m *ListCityResponse) GetCities() []*CityData {
	if m != nil {
		return m.Cities
	}
	return nil
}

func (m *ListCityResponse) GetPaging() *Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListDistrictResponse struct {
	District             []*DistrictData `protobuf:"bytes,1,rep,name=district,proto3" json:"district,omitempty"`
	Paging               *Paging         `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListDistrictResponse) Reset()         { *m = ListDistrictResponse{} }
func (m *ListDistrictResponse) String() string { return proto.CompactTextString(m) }
func (*ListDistrictResponse) ProtoMessage()    {}
func (*ListDistrictResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{5}
}

func (m *ListDistrictResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDistrictResponse.Unmarshal(m, b)
}
func (m *ListDistrictResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDistrictResponse.Marshal(b, m, deterministic)
}
func (m *ListDistrictResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDistrictResponse.Merge(m, src)
}
func (m *ListDistrictResponse) XXX_Size() int {
	return xxx_messageInfo_ListDistrictResponse.Size(m)
}
func (m *ListDistrictResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDistrictResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDistrictResponse proto.InternalMessageInfo

func (m *ListDistrictResponse) GetDistrict() []*DistrictData {
	if m != nil {
		return m.District
	}
	return nil
}

func (m *ListDistrictResponse) GetPaging() *Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

type CityData struct {
	CityId               int32    `protobuf:"varint,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	CityName             string   `protobuf:"bytes,2,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`
	ProvinceId           int32    `protobuf:"varint,3,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	ProvinceName         string   `protobuf:"bytes,4,opt,name=province_name,json=provinceName,proto3" json:"province_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityData) Reset()         { *m = CityData{} }
func (m *CityData) String() string { return proto.CompactTextString(m) }
func (*CityData) ProtoMessage()    {}
func (*CityData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{6}
}

func (m *CityData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityData.Unmarshal(m, b)
}
func (m *CityData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityData.Marshal(b, m, deterministic)
}
func (m *CityData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityData.Merge(m, src)
}
func (m *CityData) XXX_Size() int {
	return xxx_messageInfo_CityData.Size(m)
}
func (m *CityData) XXX_DiscardUnknown() {
	xxx_messageInfo_CityData.DiscardUnknown(m)
}

var xxx_messageInfo_CityData proto.InternalMessageInfo

func (m *CityData) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *CityData) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *CityData) GetProvinceId() int32 {
	if m != nil {
		return m.ProvinceId
	}
	return 0
}

func (m *CityData) GetProvinceName() string {
	if m != nil {
		return m.ProvinceName
	}
	return ""
}

type DistrictData struct {
	DistrictId           int32    `protobuf:"varint,1,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	DistrictName         string   `protobuf:"bytes,2,opt,name=district_name,json=districtName,proto3" json:"district_name,omitempty"`
	CityId               int32    `protobuf:"varint,3,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	CityName             string   `protobuf:"bytes,4,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistrictData) Reset()         { *m = DistrictData{} }
func (m *DistrictData) String() string { return proto.CompactTextString(m) }
func (*DistrictData) ProtoMessage()    {}
func (*DistrictData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{7}
}

func (m *DistrictData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistrictData.Unmarshal(m, b)
}
func (m *DistrictData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistrictData.Marshal(b, m, deterministic)
}
func (m *DistrictData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistrictData.Merge(m, src)
}
func (m *DistrictData) XXX_Size() int {
	return xxx_messageInfo_DistrictData.Size(m)
}
func (m *DistrictData) XXX_DiscardUnknown() {
	xxx_messageInfo_DistrictData.DiscardUnknown(m)
}

var xxx_messageInfo_DistrictData proto.InternalMessageInfo

func (m *DistrictData) GetDistrictId() int32 {
	if m != nil {
		return m.DistrictId
	}
	return 0
}

func (m *DistrictData) GetDistrictName() string {
	if m != nil {
		return m.DistrictName
	}
	return ""
}

func (m *DistrictData) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *DistrictData) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

type FilterPaging struct {
	Filter               *FilterKey `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Pagination           *Paging    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FilterPaging) Reset()         { *m = FilterPaging{} }
func (m *FilterPaging) String() string { return proto.CompactTextString(m) }
func (*FilterPaging) ProtoMessage()    {}
func (*FilterPaging) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{8}
}

func (m *FilterPaging) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterPaging.Unmarshal(m, b)
}
func (m *FilterPaging) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterPaging.Marshal(b, m, deterministic)
}
func (m *FilterPaging) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterPaging.Merge(m, src)
}
func (m *FilterPaging) XXX_Size() int {
	return xxx_messageInfo_FilterPaging.Size(m)
}
func (m *FilterPaging) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterPaging.DiscardUnknown(m)
}

var xxx_messageInfo_FilterPaging proto.InternalMessageInfo

func (m *FilterPaging) GetFilter() *FilterKey {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *FilterPaging) GetPagination() *Paging {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type IsRemoved struct {
	IsRemoved            bool     `protobuf:"varint,1,opt,name=is_removed,json=isRemoved,proto3" json:"is_removed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsRemoved) Reset()         { *m = IsRemoved{} }
func (m *IsRemoved) String() string { return proto.CompactTextString(m) }
func (*IsRemoved) ProtoMessage()    {}
func (*IsRemoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{9}
}

func (m *IsRemoved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsRemoved.Unmarshal(m, b)
}
func (m *IsRemoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsRemoved.Marshal(b, m, deterministic)
}
func (m *IsRemoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsRemoved.Merge(m, src)
}
func (m *IsRemoved) XXX_Size() int {
	return xxx_messageInfo_IsRemoved.Size(m)
}
func (m *IsRemoved) XXX_DiscardUnknown() {
	xxx_messageInfo_IsRemoved.DiscardUnknown(m)
}

var xxx_messageInfo_IsRemoved proto.InternalMessageInfo

func (m *IsRemoved) GetIsRemoved() bool {
	if m != nil {
		return m.IsRemoved
	}
	return false
}

type CityKey struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityKey) Reset()         { *m = CityKey{} }
func (m *CityKey) String() string { return proto.CompactTextString(m) }
func (*CityKey) ProtoMessage()    {}
func (*CityKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{10}
}

func (m *CityKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityKey.Unmarshal(m, b)
}
func (m *CityKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityKey.Marshal(b, m, deterministic)
}
func (m *CityKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityKey.Merge(m, src)
}
func (m *CityKey) XXX_Size() int {
	return xxx_messageInfo_CityKey.Size(m)
}
func (m *CityKey) XXX_DiscardUnknown() {
	xxx_messageInfo_CityKey.DiscardUnknown(m)
}

var xxx_messageInfo_CityKey proto.InternalMessageInfo

func (m *CityKey) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FilterKey struct {
	ProvinceId           int32    `protobuf:"varint,1,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Keyword              string   `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	CityId               int32    `protobuf:"varint,3,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterKey) Reset()         { *m = FilterKey{} }
func (m *FilterKey) String() string { return proto.CompactTextString(m) }
func (*FilterKey) ProtoMessage()    {}
func (*FilterKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{11}
}

func (m *FilterKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterKey.Unmarshal(m, b)
}
func (m *FilterKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterKey.Marshal(b, m, deterministic)
}
func (m *FilterKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterKey.Merge(m, src)
}
func (m *FilterKey) XXX_Size() int {
	return xxx_messageInfo_FilterKey.Size(m)
}
func (m *FilterKey) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterKey.DiscardUnknown(m)
}

var xxx_messageInfo_FilterKey proto.InternalMessageInfo

func (m *FilterKey) GetProvinceId() int32 {
	if m != nil {
		return m.ProvinceId
	}
	return 0
}

func (m *FilterKey) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *FilterKey) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type Paging struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              int32    `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paging) Reset()         { *m = Paging{} }
func (m *Paging) String() string { return proto.CompactTextString(m) }
func (*Paging) ProtoMessage()    {}
func (*Paging) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{12}
}

func (m *Paging) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paging.Unmarshal(m, b)
}
func (m *Paging) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paging.Marshal(b, m, deterministic)
}
func (m *Paging) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paging.Merge(m, src)
}
func (m *Paging) XXX_Size() int {
	return xxx_messageInfo_Paging.Size(m)
}
func (m *Paging) XXX_DiscardUnknown() {
	xxx_messageInfo_Paging.DiscardUnknown(m)
}

var xxx_messageInfo_Paging proto.InternalMessageInfo

func (m *Paging) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Paging) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *Paging) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RoleData struct {
	RoleId               int32             `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName             string            `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	ProjectId            int32             `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Permissions          []*PermissionData `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RoleData) Reset()         { *m = RoleData{} }
func (m *RoleData) String() string { return proto.CompactTextString(m) }
func (*RoleData) ProtoMessage()    {}
func (*RoleData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{13}
}

func (m *RoleData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleData.Unmarshal(m, b)
}
func (m *RoleData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleData.Marshal(b, m, deterministic)
}
func (m *RoleData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleData.Merge(m, src)
}
func (m *RoleData) XXX_Size() int {
	return xxx_messageInfo_RoleData.Size(m)
}
func (m *RoleData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleData.DiscardUnknown(m)
}

var xxx_messageInfo_RoleData proto.InternalMessageInfo

func (m *RoleData) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RoleData) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *RoleData) GetProjectId() int32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *RoleData) GetPermissions() []*PermissionData {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type PermissionData struct {
	PermissionId         int32    `protobuf:"varint,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	PermissionName       string   `protobuf:"bytes,2,opt,name=permission_name,json=permissionName,proto3" json:"permission_name,omitempty"`
	ProjectId            int32    `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SiteId               int32    `protobuf:"varint,4,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionData) Reset()         { *m = PermissionData{} }
func (m *PermissionData) String() string { return proto.CompactTextString(m) }
func (*PermissionData) ProtoMessage()    {}
func (*PermissionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dad298b5c4dee33, []int{14}
}

func (m *PermissionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionData.Unmarshal(m, b)
}
func (m *PermissionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionData.Marshal(b, m, deterministic)
}
func (m *PermissionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionData.Merge(m, src)
}
func (m *PermissionData) XXX_Size() int {
	return xxx_messageInfo_PermissionData.Size(m)
}
func (m *PermissionData) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionData.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionData proto.InternalMessageInfo

func (m *PermissionData) GetPermissionId() int32 {
	if m != nil {
		return m.PermissionId
	}
	return 0
}

func (m *PermissionData) GetPermissionName() string {
	if m != nil {
		return m.PermissionName
	}
	return ""
}

func (m *PermissionData) GetProjectId() int32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *PermissionData) GetSiteId() int32 {
	if m != nil {
		return m.SiteId
	}
	return 0
}

func init() {
	proto.RegisterType((*ProvinceData)(nil), "go.micro.srv.CityService.ProvinceData")
	proto.RegisterType((*ListProvinceData)(nil), "go.micro.srv.CityService.ListProvinceData")
	proto.RegisterType((*EmptyRequest)(nil), "go.micro.srv.CityService.EmptyRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.CityService.Response")
	proto.RegisterType((*ListCityResponse)(nil), "go.micro.srv.CityService.ListCityResponse")
	proto.RegisterType((*ListDistrictResponse)(nil), "go.micro.srv.CityService.ListDistrictResponse")
	proto.RegisterType((*CityData)(nil), "go.micro.srv.CityService.CityData")
	proto.RegisterType((*DistrictData)(nil), "go.micro.srv.CityService.DistrictData")
	proto.RegisterType((*FilterPaging)(nil), "go.micro.srv.CityService.FilterPaging")
	proto.RegisterType((*IsRemoved)(nil), "go.micro.srv.CityService.IsRemoved")
	proto.RegisterType((*CityKey)(nil), "go.micro.srv.CityService.CityKey")
	proto.RegisterType((*FilterKey)(nil), "go.micro.srv.CityService.FilterKey")
	proto.RegisterType((*Paging)(nil), "go.micro.srv.CityService.Paging")
	proto.RegisterType((*RoleData)(nil), "go.micro.srv.CityService.RoleData")
	proto.RegisterType((*PermissionData)(nil), "go.micro.srv.CityService.PermissionData")
}

func init() {
	proto.RegisterFile("proto/cityservice/cityService.proto", fileDescriptor_2dad298b5c4dee33)
}

var fileDescriptor_2dad298b5c4dee33 = []byte{
	// 840 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x6e, 0xda, 0x48,
	0x14, 0xc6, 0xe0, 0x18, 0x7c, 0xec, 0x65, 0xa3, 0x51, 0xa4, 0x10, 0x76, 0xa3, 0x65, 0x27, 0xd2,
	0x2e, 0xca, 0x05, 0x2b, 0xb1, 0x37, 0xab, 0xdd, 0x9b, 0x4d, 0x43, 0xaa, 0xd2, 0xf4, 0x27, 0x75,
	0xef, 0xfa, 0x47, 0x1d, 0xcf, 0x94, 0x4c, 0x03, 0xd8, 0xb5, 0x27, 0x54, 0xbc, 0x40, 0x55, 0x55,
	0xea, 0x4d, 0x55, 0xf5, 0x25, 0xfa, 0x52, 0x7d, 0x94, 0x6a, 0xc6, 0x3f, 0x18, 0x1a, 0xdc, 0x41,
	0x69, 0xee, 0x66, 0xce, 0xef, 0xf7, 0x9d, 0x73, 0xe6, 0x18, 0x60, 0x2f, 0x08, 0x7d, 0xee, 0xff,
	0xe5, 0x31, 0x3e, 0x8b, 0x68, 0x38, 0x65, 0x1e, 0x95, 0xe7, 0x87, 0xf1, 0xb9, 0x23, 0xb5, 0xa8,
	0x31, 0xf4, 0x3b, 0x63, 0xe6, 0x85, 0x7e, 0x27, 0x0a, 0xa7, 0x9d, 0xc3, 0xb9, 0x1e, 0x1f, 0x82,
	0x7d, 0x12, 0xfa, 0x53, 0x36, 0xf1, 0x68, 0xcf, 0xe5, 0x2e, 0xaa, 0x43, 0x99, 0x91, 0x86, 0xd6,
	0xd2, 0xda, 0x1b, 0x4e, 0x99, 0x11, 0xb4, 0x07, 0x3f, 0x05, 0x89, 0x7e, 0x30, 0x71, 0xc7, 0xb4,
	0x51, 0x6e, 0x69, 0x6d, 0xd3, 0xb1, 0x53, 0xe1, 0x3d, 0x77, 0x4c, 0xf1, 0x07, 0x0d, 0x36, 0xef,
	0xb0, 0x88, 0x2f, 0x44, 0xea, 0x81, 0x99, 0x1a, 0x45, 0x0d, 0xad, 0x55, 0x69, 0x5b, 0xdd, 0x3f,
	0x3a, 0xab, 0x70, 0x74, 0xf2, 0xae, 0xce, 0xdc, 0x11, 0xfd, 0x03, 0x46, 0xe0, 0x0e, 0xd9, 0x64,
	0x28, 0x13, 0x5b, 0xdd, 0x56, 0x41, 0x08, 0x69, 0xe7, 0x24, 0xf6, 0xb8, 0x0e, 0xf6, 0xd1, 0x38,
	0xe0, 0x33, 0x87, 0xbe, 0xba, 0xa0, 0x11, 0xc7, 0xbf, 0x42, 0xcd, 0xa1, 0x51, 0xe0, 0x4f, 0x22,
	0x8a, 0x36, 0xa1, 0x32, 0x8e, 0x86, 0x92, 0xa6, 0xe9, 0x88, 0x23, 0x7e, 0x9b, 0x50, 0x10, 0x01,
	0x33, 0xb3, 0x7f, 0xc1, 0xf0, 0x18, 0x67, 0x19, 0x7e, 0xbc, 0x3a, 0xb9, 0x38, 0x4b, 0xec, 0x89,
	0xc7, 0x15, 0x80, 0x7f, 0xd4, 0x60, 0x4b, 0x40, 0xe9, 0xb1, 0x88, 0x87, 0xcc, 0xe3, 0x19, 0x9c,
	0x1b, 0x50, 0x23, 0x89, 0xec, 0xfb, 0x05, 0x4d, 0xbd, 0x25, 0xa8, 0xcc, 0xef, 0x0a, 0xb0, 0xde,
	0x68, 0x50, 0x4b, 0x59, 0xa2, 0x6d, 0xa8, 0x8a, 0x29, 0x1b, 0x64, 0xb3, 0x22, 0x68, 0xcf, 0xfa,
	0x04, 0xfd, 0x02, 0xa6, 0x54, 0xe4, 0x66, 0xa5, 0x26, 0x04, 0x62, 0x4e, 0xd0, 0x6f, 0x60, 0x65,
	0xc3, 0xc4, 0x48, 0xa3, 0x22, 0x3d, 0x21, 0x15, 0xf5, 0x2f, 0x99, 0x36, 0xfd, 0x92, 0x69, 0x7b,
	0xa7, 0x81, 0x9d, 0x67, 0x27, 0xc2, 0xa6, 0xfc, 0xe6, 0x80, 0x20, 0x15, 0xc5, 0x61, 0x33, 0x83,
	0xfc, 0x10, 0xa7, 0x42, 0x09, 0x2e, 0x47, 0xa9, 0xb2, 0x9a, 0x92, 0xbe, 0x48, 0x09, 0xbf, 0xd7,
	0xc0, 0xbe, 0xc9, 0x46, 0x9c, 0x86, 0x71, 0xb9, 0xd0, 0x7f, 0x60, 0xbc, 0x90, 0x77, 0x89, 0xc3,
	0xea, 0xee, 0xad, 0x2e, 0x70, 0xec, 0x77, 0x4c, 0x67, 0x4e, 0xe2, 0x82, 0xfe, 0x07, 0x90, 0xd5,
	0x76, 0x39, 0xf3, 0x27, 0xca, 0x1d, 0xca, 0xf9, 0xe0, 0x7d, 0x30, 0xfb, 0x91, 0x43, 0xc7, 0xfe,
	0x94, 0x12, 0xb4, 0x0b, 0xc0, 0xa2, 0x41, 0x18, 0xdf, 0x24, 0x9e, 0x9a, 0x63, 0xb2, 0x54, 0x8d,
	0x77, 0xa0, 0x2a, 0xa2, 0x1d, 0xd3, 0xd9, 0xf2, 0xb3, 0xc7, 0x03, 0x30, 0x33, 0x74, 0xcb, 0x6d,
	0xd3, 0xbe, 0x69, 0x5b, 0x03, 0xaa, 0xe7, 0x74, 0xf6, 0xda, 0x0f, 0x49, 0x52, 0xd9, 0xf4, 0xba,
	0xb2, 0xa8, 0xf8, 0x2e, 0x18, 0x49, 0xc1, 0x10, 0xe8, 0x81, 0x3b, 0xa4, 0x49, 0x58, 0x79, 0x46,
	0x3b, 0x50, 0x0b, 0x68, 0x38, 0x90, 0xf2, 0xb2, 0x94, 0x57, 0x03, 0x59, 0x61, 0x8a, 0xb6, 0x60,
	0xc3, 0xf3, 0x2f, 0x26, 0x3c, 0x89, 0x17, 0x5f, 0xf0, 0x67, 0x0d, 0x6a, 0x8e, 0x3f, 0xa2, 0xe9,
	0x70, 0x86, 0xfe, 0x28, 0x87, 0xd5, 0x10, 0xd7, 0xb8, 0x93, 0x52, 0x91, 0x1f, 0x4e, 0x21, 0x90,
	0xfd, 0xdf, 0x05, 0x41, 0xe9, 0x25, 0x8d, 0x87, 0x28, 0x8e, 0x6e, 0x26, 0x92, 0x3e, 0x41, 0xb7,
	0xc1, 0x0a, 0x68, 0x38, 0x66, 0x51, 0xc4, 0xfc, 0x49, 0xd4, 0xd0, 0xe5, 0xfb, 0x6b, 0x17, 0xf4,
	0x26, 0x33, 0x96, 0x2f, 0x30, 0xef, 0x8c, 0x3f, 0x69, 0x50, 0x5f, 0xd4, 0xcb, 0xc9, 0xcf, 0x24,
	0x73, 0xe4, 0xf6, 0x5c, 0xd8, 0x27, 0xe8, 0x4f, 0xf8, 0x39, 0x67, 0x94, 0x63, 0x51, 0x9f, 0x8b,
	0x55, 0xb8, 0x6c, 0x43, 0x35, 0x62, 0x5c, 0x16, 0x48, 0x8f, 0x0b, 0x24, 0xae, 0x7d, 0xd2, 0xfd,
	0x62, 0x81, 0x2e, 0x48, 0xa0, 0xc7, 0x60, 0xdd, 0xa2, 0xee, 0x88, 0x9f, 0x79, 0x67, 0xd4, 0x3b,
	0x47, 0x05, 0x7b, 0x26, 0xbf, 0x63, 0x9b, 0x05, 0x0b, 0x32, 0xdd, 0x62, 0xb8, 0x84, 0x9e, 0x80,
	0x2e, 0xf6, 0x5b, 0x51, 0xd4, 0xfc, 0x93, 0x6a, 0xee, 0xaf, 0xb6, 0x5b, 0x5e, 0xd9, 0xb8, 0x84,
	0x1e, 0x80, 0xd1, 0xa3, 0xdc, 0x65, 0x23, 0xf4, 0x7b, 0xf1, 0xba, 0x3e, 0xa6, 0xb3, 0xa6, 0xc2,
	0x46, 0xc7, 0x25, 0x74, 0x1f, 0x2a, 0x07, 0x84, 0x20, 0x05, 0x63, 0xc5, 0x80, 0x27, 0xa0, 0x1f,
	0x11, 0xc6, 0x7f, 0x60, 0x44, 0x07, 0x8c, 0xf8, 0x59, 0xab, 0xb0, 0x2e, 0xd8, 0x49, 0xd9, 0xf2,
	0xc0, 0x25, 0x74, 0x06, 0x76, 0xfe, 0x3b, 0xa4, 0xdc, 0xaf, 0x4e, 0x71, 0xbf, 0x96, 0xbf, 0x6b,
	0xb8, 0x84, 0x9e, 0x42, 0x3d, 0xee, 0x59, 0x96, 0x4b, 0x81, 0x85, 0xe2, 0xc7, 0x0f, 0x97, 0xd0,
	0x00, 0xac, 0x03, 0x42, 0x54, 0x78, 0xe4, 0x1d, 0xd7, 0x48, 0xf0, 0x1c, 0x6c, 0xd1, 0xcf, 0x6b,
	0xcc, 0xf0, 0x08, 0xea, 0x71, 0x63, 0xd6, 0xa9, 0x90, 0x62, 0x9f, 0xe3, 0xf2, 0xa4, 0xbf, 0xc0,
	0x90, 0xe2, 0xaf, 0xb4, 0xa6, 0xa2, 0xdd, 0xbc, 0x3c, 0xd7, 0x98, 0xe1, 0x59, 0x5a, 0x9e, 0xb5,
	0x73, 0xa8, 0xad, 0xac, 0xd3, 0x74, 0x40, 0xaf, 0x91, 0x03, 0x89, 0x9f, 0x9b, 0x4a, 0x86, 0x75,
	0xd6, 0xe3, 0x62, 0x96, 0x53, 0x43, 0xfe, 0x23, 0xf8, 0xfb, 0x6b, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xc4, 0x3b, 0x85, 0x5d, 0x38, 0x0c, 0x00, 0x00,
}
