package constant

const (
	HOST_POSTGRESQL  = "localhost"
	PORT_POSTGRESQL  = 5432
	POSTGRESQL_USERNAME ="postgres"
	POSTGRESQL_PASSWORD ="Password1!"
	POSTGRESQL_DBNAME ="city"
	SSL_MODE="disable"
	REDIS_HOST="localhost:6379"
	REDIS_PASSWORD=""
	REDIS_DB=0
	REDIS_HOST_ENV="GO_REDIS_ADDR"
	REDIS_PASSWORD_ENV="GO_REDIS_PASSWORD"
	REDIS_DB_ENV="GO_REDIS_DB"
	POSTGRESQL_DIALECT = "postgres"
	MYSQL_DIALECT = "mysql"
	SQLITE_DIALECT = "sqlite3"
	SQL_SERVER_DIALECT = "mssql"
	CITY_TABLE_NAME = "city"
	DISTRICT_TABLE_NAME = "district"
	PROVINCE_TABLE_NAME = "province"
)
